### ISSUE TITLE
Upgrade to Ember 5

### ISSUE THREAD

**Issue by rohitpaulk** [codecrafters-io/frontend#993]
```[tasklist]
### Tasks
- [x] Clear muted deprecation warnings
- [x] Fix deprecations that are dropped in Ember 5
- [x] Upgrade addons causing deprecation warnings
- [x] Mute remaining deprecation warnings
- [x] Run `ember-cli-upgrade`
- [x] Fix all dependency problems after upgrade
- [x] Fix all test errors after upgrade
```
